---
  - name: installing custom facts
    hosts: 192.168.56.113
    vars:
      remote_dir: /etc/ansible/facts.d
      facts_file: localfacts.fact
    tasks:
      - name: create remote directory
        file:
          state: directory
          recurse: yes
          path: "{{ remote_dir }}"
      - name: install new facts
        copy:
          src: "{{ facts_file }}"
          dest: "{{ remote_dir }}"
