---
  - name: find the ipv4 address of the managed hosts
    hosts: all
    #gather_facts: no
    tasks:
      - name: show IP addresses
        debug: 
          msg: This host uses IP address {{ ansible_facts.default_ipv4.address }} 
