weblogic:
 hosts: 
   slave1:
   slave2:
 vars:
  ansible_user: root
  source_path: /opt
  destination_path: /tmp
  
db:
  hosts:
    slave1: 
  vars:
  ansible_user: root
  source_path: /opt
  destination_path: /tmp 
